### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by dgarciagud** [paduel/fhub#4]
Trying to obtain intraday data I obtain the following error: 

data = hub.candle('AMZN', resolution='60', end="2020-05-22")
Traceback (most recent call last):

  File "<ipython-input-160-9ae02778b730>", line 1, in <module>
    data = hub.candle('AMZN', resolution='60', end="2020-05-22")

  File "C:\Users\casa\Anaconda3\lib\site-packages\fhub\utils.py", line 143, in helper
    return func(clase, *args, **kwargs)

  File "C:\Users\casa\Anaconda3\lib\site-packages\fhub\utils.py", line 134, in helper
    return func(clase, *args, **kwargs)

  File "C:\Users\casa\Anaconda3\lib\site-packages\fhub\core.py", line 566, in candle
    'from': _unixtime(start),

  File "C:\Users\casa\Anaconda3\lib\site-packages\fhub\utils.py", line 169, in _unixtime
    return int(datetime.strptime(_normalize_date(date), "%Y-%m-%d").timestamp())

OSError: [Errno 22] Invalid argument

**Comment by pesapower** [comment]
Hi, you should specify the `start` argument value when you use `candle()`.

i.e. `data = hub.candle('AMZN', resolution='60', start="2020-05-15", end="2020-05-22")`

**Comment by arogima** [comment]
Apparently it's a Python error in Windows. I didn't find that bug when developing the code on Linux.

[Timestamp conversion on windows fails with timestamps close to EPOCH](https://bugs.python.org/issue37527)

I'll find a way around it.

**Comment by pesapower** [comment]
@arogima is right, Windows has some problem to handle timestamp regarding dates before 1970 (see [here](https://stackoverflow.com/questions/59199985/why-is-datetimes-timestamp-method-returning-oserror-errno-22-invalid-a)). In particular, with my laptop (Windows 10) I have the same issue with all date before 1970/01/03 (yes 3rd January, I don't know why for the moment). I have just sent a pull request with a simple fix: if `start` argument is `None` then its value will be `"1970-01-03"`.

**Comment by dgarciagud** [comment]
> start="2020-05-15",

thanks it works when start date is introduced!

**Comment by paduel** [comment]
I update a new version 0.0.13, please @dgarciagud  check if this version solved the bug in Windows.

**Comment by dgarciagud** [comment]
this is solved @paduel.
Additionally I have to deal with to minor errors

ImportError: cannot import name 'json_normalize' from 'pandas' (C:\Users\casa\Anaconda3\lib\site-packages\pandas\__init__.py)

using from pandas.io.json import json_normalize instead of directly from pandas.

And another with NA from pandas.

**Comment by paduel** [comment]
> this is solved @paduel.
> Additionally I have to deal with to minor errors
> 
> ImportError: cannot import name 'json_normalize' from 'pandas' (C:\Users\casa\Anaconda3\lib\site-packages\pandas__init__.py)
> 
> using from pandas.io.json import json_normalize instead of directly from pandas.
> 
> And another with NA from pandas.

Nice!

You must to update Pandas for the other error.
